apiVersion: v2
name: KapitelShelf
description: KapitelShelf helm chart for deploying the KapitelShelf application
  stack, including optional PostgreSQL database support. Provides a flexible
  setup for both self-contained and external database configurations.
type: application
version: 0.3.3
appVersion: "N/A"
dependencies:
  - name: postgresql
    version: 16.6.6
    repository: https://charts.bitnami.com/bitnami
    condition: global.deployPostgresql
home: "https://github.com/ThomasMiller01/KapitelShelf"
sources:
  [
    "https://github.com/ThomasMiller01/KapitelShelf/tree/main/helm/kapitelshe\
      lf"
  ]
