apiVersion: v1
entries:
  KapitelShelf:
  - apiVersion: v2
    appVersion: N/A
    created: "2026-01-14T13:57:55.570802665Z"
    dependencies:
    - condition: global.deployPostgresql
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.6.6
    description: KapitelShelf helm chart for deploying the KapitelShelf application
      stack, including optional PostgreSQL database support. Provides a flexible setup
      for both self-contained and external database configurations.
    digest: 573dcc2d422408f583e56edeb2c8a61acc5d78792bec19003933c31d2806e2af
    home: https://github.com/ThomasMiller01/KapitelShelf
    name: KapitelShelf
    sources:
    - https://github.com/ThomasMiller01/KapitelShelf/tree/main/helm/kapitelshelf
    type: application
    urls:
    - https://thomasmiller01.github.io/KapitelShelf/helm/KapitelShelf-0.3.3.tgz
    version: 0.3.3
generated: "2026-01-14T13:57:55.56523534Z"
