apiVersion: v1
entries:
  KapitelShelf:
  - apiVersion: v2
    appVersion: N/A
    created: "2026-02-12T20:30:44.295411786Z"
    dependencies:
    - condition: global.deployPostgresql
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 16.6.6
    description: KapitelShelf helm chart for deploying the KapitelShelf application
      stack, including optional PostgreSQL database support. Provides a flexible setup
      for both self-contained and external database configurations.
    digest: f258eb0f371a62caafa0f68383d337f8ed1df1664e96239df3015cf449f3ccdb
    home: https://github.com/ThomasMiller01/KapitelShelf
    name: KapitelShelf
    sources:
    - https://github.com/ThomasMiller01/KapitelShelf/tree/main/helm/kapitelshelf
    type: application
    urls:
    - https://thomasmiller01.github.io/KapitelShelf/helm/KapitelShelf-0.3.4.tgz
    version: 0.3.4
generated: "2026-02-12T20:30:44.289280873Z"
